# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83430427d2b1f126100be09517a16dd5e25fc661edf89fd3a0c23fae322d352f356ce7aed1c27775b2864378800e1df112b20a72bea5148617873934ec19c331

test:
  secret_key_base: 6e0076288b7f56dfda20fc540814fa070a16ff59c297e49e71f8716278242ee59068163b229bb8c776a7bd2c20f1406ffb1276e7c096a65572d28c6ae7c6308e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
